name: ridy
description: Rider Application of Taxi

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.0+104

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  artemis: 7.7.0-beta
  country_code_picker: ^2.0.2
  country_codes: ^2.2.0
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  facebook_app_events: 0.15.0
  file_picker: ^4.6.1
  firebase_analytics: 9.1.10
  firebase_auth: 3.3.20
  firebase_crashlytics: 2.8.2
  firebase_core: 1.18.0
  firebase_messaging: 11.4.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_chat_types: ^3.4.3
  flutter_chat_ui: ^1.6.2
  google_maps_webservice: 0.0.20-nullsafety.5
  google_api_headers: ^1.3.0
  flutter_map: ^1.1.1
  flutter_map_location_marker: ^4.1.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^8.0.1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.8
  gql: 0.13.1
  graphql_flutter: ^5.1.1-beta.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  json_annotation: ^4.5.0
  latlong2: ^0.8.1
  lifecycle: ^0.5.0
  meta: ^1.3.0
  modal_bottom_sheet: ^2.1.0
  osm_nominatim: ^2.0.1
  package_info_plus: ^1.4.0
  share_plus: ^4.0.10
  shimmer: ^2.0.0
  sms_autofill: ^2.1.2
  timeago_flutter: ^1.1.0
  url_launcher: ^6.1.4
  velocity_x: ^3.5.1
  client_shared:
    path: ../../libs/client-shared

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  # flutter_test:
  #   sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - images/default-user-image.png
    - images/expanding_marker.json
    - images/3532-car.json
    - images/marker.png
    - images/marker_taxi.png
    - images/searching.png
    - images/booking_confirmed.png
    - images/logo.png
    - google_fonts/

flutter_intl:
  enabled: true